cppcheck:
    - type : command
      command : cppcheck --template {file}:{line},{severity},{id},{message} --quiet --inline-suppr ascenddk/common/ 2> cppcheck.log
    - type : command
      command : cat cppcheck.log
    - type : function
      command : 
          function_name : check_file_is_empty
          args :
              - cppcheck.log
          expected_result : True