static_check:
    - type: command
      command:
          cmd: find ${ASCEND_ROOT_PATH}/ascenddk -path "${ASCEND_ROOT_PATH}/ascenddk/common/*.cpp"
               -o -path "${ASCEND_ROOT_PATH}/ascenddk/common/*.h" > ${BUILD_TEMP_PATH}/warncheck_filelist.log
    - type: function
      command:
          funcion_name: warn_check
          args:
              - ${BUILD_TEMP_PATH}/warncheck_filelist.log
              - aarch64-linux-gnu-g++ -std=c++11 -Wall 
                __WARN_CHECK_HEADERS__ __WARN_CHECK_FILE__ 2>&1 | tee -a ${BUILD_TEMP_PATH}/warncheck.log
    - type: command
      command:
          cmd: cat ${BUILD_TEMP_PATH}/warncheck.log
    - type: function
      command: 
          function_name: check_file_is_empty
          args:
              - ${BUILD_TEMP_PATH}/warncheck.log
          expected_result: True