cppcheck:
    - type : command
      command : cppcheck --template {file}:{line},{severity},{id},{message} 
                --quiet --inline-suppr ascenddk/common/ 
                2>&1 | tee ${ASCEND_ROOT_PATH}/cppcheck.log
    - type : function
      command : 
          function_name : check_file_is_empty
          args :
              - ${ASCEND_ROOT_PATH}/cppcheck.log
          expected_result : True