install:
    - git clone --depth=50 --branch=$TRAVIS_BRANCH https://github.com/Ascend/tools.git ${ASCEND_ROOT_PATH}/tools 
    - cd ${ASCEND_ROOT_PATH}/tools && git checkout
    - unzip mini_mind_studio_developerkit.rar
    - sudo mkdir -p ${DDK_HOME}
    - tar -zxvf MSpore_DDK* -C ${DDK_HOME}/../
    - sudo chmod -R 775 /root
    - wget -x -P ${LLT_ROOT_PATH}/src "https://github.com/abseil/googletest/archive/release-1.8.1.tar.gz"
    - tar -zxvf ${LLT_ROOT_PATH}/src/googletest-release*.tar.gz -C ${LLT_ROOT_PATH}/src
    - cd ${LLT_ROOT_PATH}/src/googletest-release*/googletest && cmake -DCMAKE_CXX_FLAGS="-std=c++0x" ./ && make
    - cd ${LLT_ROOT_PATH}/src/googletest-release*/googlemock && cmake -DCMAKE_CXX_FLAGS="-std=c++0x" ./ && make
    - mkdir -p ${LLT_ROOT_PATH}/gtest && mkdir -p ${LLT_ROOT_PATH}/mockcpp
    - cp -R ${LLT_ROOT_PATH}/src/googletest-release*/googletest/include ${LLT_ROOT_PATH}/gtest
    - cp -R ${LLT_ROOT_PATH}/src/googletest-release*/googletest/lib ${LLT_ROOT_PATH}/gtest
    - cp -R ${LLT_ROOT_PATH}/src/googletest-release*/googlemock/include ${LLT_ROOT_PATH}/mockcpp
    - cp -R ${LLT_ROOT_PATH}/src/googletest-release*/googlemock/lib ${LLT_ROOT_PATH}/mockcpp
    - cd ${ASCEND_ROOT_PATH}
    - mkdir -p ${BUILD_TEMP_PATH}