install:
    - export ASCEND_ROOT_PATH=${HOME}/build/Ascend
    - export BUILD_ROOT_PATH=${HOME}/build/Ascend/scripts/travis_scripts
    - export BUILD_TEMP_PATH=${BUILD_ROOT_PATH}/temp
    - export DDK_HOME=/root/tools/che/ddk/ddk
    - export LLT_ROOT_PATH=${HOME}/build/googletest
    - cd ${ASCEND_ROOT_PATH}
    - mkdir -p ${BUILD_TEMP_PATH}