install:
    - export ASCEND_ROOT_PATH=${HOME}/build/Ascend
    - export BUILD_TEMP_PATH=${HOME}/build/Ascend/scripts/travis_scripts/temp
    - export DDK_HOME=/root/tools/che/ddk/ddk
    - export LLT_ROOT_PATH=${HOME}/build/googletest
    - git clone --depth=50 --branch=$TRAVIS_BRANCH https://github.com/Ascend/tools.git ${ASCEND_ROOT_PATH}/tools 
    - cd ${ASCEND_ROOT_PATH}/tools && git checkout
    - unzip mini_mind_studio_developerkit.rar
    - sudo mkdir -p ${DDK_ROOT_PATH}
    - tar -zxvf MSpore_DDK* -C ${DDK_ROOT_PATH}
    - sudo chmod -R 775 /root
    - cd ${ASCEND_ROOT_PATH}
    - mkdir -p ${BUILD_TEMP_PATH}