install:
    - git clone --depth=50 --branch=$TRAVIS_BRANCH https://github.com/Ascend/tools.git ${ASCEND_ROOT_PATH}/tools 
    - cd ${ASCEND_ROOT_PATH}/tools && git checkout
    - unzip mini_mind_studio_developerkit.rar
    - tar -zxvf MSpore_DDK*
    - cd ${ASCEND_ROOT_PATH}
    - mkdir -p ${BUILD_TEMP_PATH}