install:
    - sudo apt-get update #travis CI: need to update before install
    - sudo apt-get -y install gcc-aarch64-linux-gnu
    - sudo apt-get -y install g++-aarch64-linux-gnu
    - wget -P ${LLT_ROOT_PATH}/src/gtest --no-check-certificate -N "https://github.com/abseil/googletest/archive/release-1.8.1.tar.gz"
    - tar -zxvf ${LLT_ROOT_PATH}/src/gtest/release*.tar.gz -C ${LLT_ROOT_PATH}/src/gtest
    - cmake -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ -DCMAKE_CXX_FLAGS="-std=c++0x" ${LLT_ROOT_PATH}/src/gtest/googletest-release*/googletest 
      && make -C ${LLT_ROOT_PATH}/src/gtest/googletest-release*/googletest
    - mkdir -p ${LLT_ROOT_PATH}/gtest/lib
    - cp -R ${LLT_ROOT_PATH}/src/gtest/googletest-release*/googletest/include ${LLT_ROOT_PATH}/gtest/
    - cp -R ${LLT_ROOT_PATH}/src/gtest/googletest-release*/googletest/lib*.a ${LLT_ROOT_PATH}/gtest/lib/
    - wget -P ${LLT_ROOT_PATH}/src/mockcpp --no-check-certificate -N "https://bitbucket.org/godsme/mockcpp/get/06ad37ddc45c.zip"
    - unzip -o ${LLT_ROOT_PATH}/src/mockcpp/*.zip -d ${LLT_ROOT_PATH}/src/mockcpp
    - cmake -DMOCKCPP_XUNIT=gtest -DMOCKCPP_XUNIT_HOME=${LLT_ROOT_PATH}/src/gtest/googletest-release-1.8.1/googletest
      -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ -DCMAKE_CXX_FLAGS="-std=c++0x" -DCMAKE_INSTALL_PREFIX=${LLT_ROOT_PATH}/src/mockcpp/godsme-mockcpp*/install ${LLT_ROOT_PATH}/src/mockcpp/godsme-mockcpp*
      && make install -C ${LLT_ROOT_PATH}/src/mockcpp/godsme-mockcpp*
    - mkdir -p ${LLT_ROOT_PATH}/mockcpp
    - cp -R ${LLT_ROOT_PATH}/src/mockcpp/godsme-mockcpp*/install/* ${LLT_ROOT_PATH}/mockcpp/