language: cpp

dist: xenial

#default before_install, clone Ascend/tools as default, it can be overwrited by jobs
before_install: python3 $HOME/Ascend/ascenddk/scripts/install/install.py before_install_clone_tools

#default install, it can be overwrited by jobs
install: python3 $HOME/Ascend/ascenddk/scripts/install/install.py install

jobs:
    include:
        - stage: ascenddk llt and sc
          name: "static_check_cppcheck"
          before_install: true
          install: python3 $HOME/Ascend/ascenddk/scripts/install/install.py cppcheck
          script: python3 $HOME/Ascend/ascenddk/scripts/script/static_check_run.py cppcheck
        - name: "ut_presentor"
          script: echo "running"
        - name: "st_presentor"
          script: echo "running"