install:
    - git clone --depth=50 --branch=$TRAVIS_BRANCH https://github.com/Ascend/tools.git $TRAVIS_BUILD_DIR/../../Ascend/tools 
    - cd $TRAVIS_BUILD_DIR/../../Ascend/tools && git checkout
    - cd $TRAVIS_BUILD_DIR/../