warn_check_command:
    args:
        - 
            __WARN_CHECK_COMMAND__: make -C ${ASCEND_ROOT_PATH}/ascenddk/common/presenter/agent
        -
            __WARN_CHECK_COMMAND__: make -C ${ASCEND_ROOT_PATH}/ascenddk/common/osd
        - 
            __WARN_CHECK_COMMAND__: make -C ${ASCEND_ROOT_PATH}/ascenddk/common/utils/ascend_ezdvpp
        -
            __WARN_CHECK_COMMAND__: make -C ${ASCEND_ROOT_PATH}/ascenddk/common/ascendcamera
warn_check_function:
    args:
        - arg_key_value:
            checked_path: ${ASCEND_ROOT_PATH}/ascenddk/engine/computervision/facedetectionapp/facedetectionapp/CameraDatasets
            headers_list:
                - ${ASCEND_ROOT_PATH}/ascenddk/engine/computervision/facedetectionapp/facedetectionapp/CameraDatasets
                - ${ASCEND_ROOT_PATH}/ascenddk/engine/computervision/facedetectionapp/facedetectionapp/FaceDetectionInferenceEngine
                - ${ASCEND_ROOT_PATH}/ascenddk/engine/computervision/facedetectionapp/facedetectionapp/FaceDetectionPostProcess
                - ${ASCEND_ROOT_PATH}/ascenddk/engine/computervision/facedetectionapp/facedetectionapp/FaceDetectionPreProcess
                - ${ASCEND_ROOT_PATH}/ascenddk/engine/computervision/facedetectionapp/facedetectionapp/common/include
                - ${DDK_ROOT_PATH}/include/inc
                - ${DDK_ROOT_PATH}/include/inc/custom
                - ${DDK_ROOT_PATH}/include/inc/ascenddk
                - ${DDK_ROOT_PATH}/include/third_party/opencv/include
                - ${DDK_ROOT_PATH}/include/third_party/protobuf/include
                - ${DDK_ROOT_PATH}/include/third_party/cereal/include
                - ${DDK_ROOT_PATH}/include/libc_sec/include