cppcheck:
    - type: command
      cmd: rm -rf ${BUILD_TEMP_PATH}/*
    - type: command
      cmd: cppcheck --template {file}:{line},{severity},{id},{message} 
           --quiet --inline-suppr -i${ASCEND_ROOT_PATH}/ascenddk/test
           ${ASCEND_ROOT_PATH}/ascenddk 2>&1 | tee -a ${BUILD_TEMP_PATH}/cppcheck.log
    - type: function
      function_name: check_file_is_empty
      params:
          - ${BUILD_TEMP_PATH}/cppcheck.log
      expected_result: True
pylint:
    - type: command
      cmd: rm -rf ${BUILD_TEMP_PATH}/*
    - type: function
      function_name: pylint
      params:
          cmd: pylint --rcfile=${ASCEND_ROOT_PATH}/ascenddk/scripts/travis_scripts/script/config/pylintrc -rn
               __PYLINT_PATH__ --ignore=__PYLINT_IGNORE_PATH__
      sub_params: pylint_ignored_files
      expected_result: True
warn_check:
    - type: command
      cmd: rm -rf ${BUILD_TEMP_PATH}/*
    - type: function
      function_name: warn_check
      params:
          compile_cmd: aarch64-linux-gnu-g++ -std=c++11 -Wall -c __WARN_CHECK_HEADERS__ __WARN_CHECK_FILE__ 
                       -o ${BUILD_TEMP_PATH}/__WARN_CHECK_FILE_NAME__ 2>&1 | tee -a ${BUILD_TEMP_PATH}/warncheck.log
          makefile_cmd: make -C __WARN_CHECK_MAKEFILE_PATH__ | tee -a ${BUILD_TEMP_PATH}/warncheck.log    
      expected_result: True
    - type: function
      function_name: filter_warn_check_is_none
      params:
          - ${BUILD_TEMP_PATH}/warncheck.log
      expected_result: True